name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Required for Azure Trusted Signing
      id-token: write
      # Required for vcpkg binary cache
      packages: write
    with:
      build-type: Release
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    permissions:
      contents: write
    runs-on: ubuntu-slim
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: "true"
          path: "MaterialMC-source"
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/MaterialMC-source MaterialMC-${{ env.VERSION }}
          mv MaterialMC-Linux-Qt6-Portable*/MaterialMC-portable.tar.gz MaterialMC-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv MaterialMC-Linux-aarch64-Qt6-Portable*/MaterialMC-portable.tar.gz MaterialMC-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv MaterialMC-*.AppImage/MaterialMC-*-x86_64.AppImage MaterialMC-Linux-x86_64.AppImage
          mv MaterialMC-*.AppImage.zsync/MaterialMC-*-x86_64.AppImage.zsync MaterialMC-Linux-x86_64.AppImage.zsync
          mv MaterialMC-*.AppImage/MaterialMC-*-aarch64.AppImage MaterialMC-Linux-aarch64.AppImage
          mv MaterialMC-*.AppImage.zsync/MaterialMC-*-aarch64.AppImage.zsync MaterialMC-Linux-aarch64.AppImage.zsync
          mv MaterialMC-macOS*/MaterialMC.zip MaterialMC-macOS-${{ env.VERSION }}.zip
          mv MaterialMC-macOS*/MaterialMC.dmg MaterialMC-macOS-${{ env.VERSION }}.dmg

          tar --exclude='.git' -czf MaterialMC-${{ env.VERSION }}.tar.gz MaterialMC-${{ env.VERSION }}

          for d in MaterialMC-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            ARM64="$(echo -n ${d} | grep -o arm64 || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="MaterialMC-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${ARM64}" || NAME="${NAME}-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv MaterialMC-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in MaterialMC-Windows-MinGW-w64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="MaterialMC-Windows-MinGW-w64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv MaterialMC-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: MaterialMC ${{ env.VERSION }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            MaterialMC-Linux-x86_64.AppImage
            MaterialMC-Linux-x86_64.AppImage.zsync
            MaterialMC-Linux-aarch64.AppImage
            MaterialMC-Linux-aarch64.AppImage.zsync
            MaterialMC-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            MaterialMC-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
            MaterialMC-Windows-MinGW-w64-${{ env.VERSION }}.zip
            MaterialMC-Windows-MinGW-w64-Portable-${{ env.VERSION }}.zip
            MaterialMC-Windows-MinGW-w64-Setup-${{ env.VERSION }}.exe
            MaterialMC-Windows-MSVC-arm64-${{ env.VERSION }}.zip
            MaterialMC-Windows-MSVC-arm64-Portable-${{ env.VERSION }}.zip
            MaterialMC-Windows-MSVC-arm64-Setup-${{ env.VERSION }}.exe
            MaterialMC-Windows-MSVC-${{ env.VERSION }}.zip
            MaterialMC-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            MaterialMC-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            MaterialMC-macOS-${{ env.VERSION }}.zip
            MaterialMC-macOS-${{ env.VERSION }}.dmg
            MaterialMC-${{ env.VERSION }}.tar.gz
